title: Il Catalogo BIFLOW - Toscana bilingue
baseurl: "/biflow_website"
preloadurl: "http://mizar.unive.it/catalogo_biflow/preload.js"
url: "https://tmancinelli.github.io/biflow_website"
emails: [antonio.montefusco@unive.it, sara.bischetti@unive.it, tiziana.mancinelli@unive.it]

# Build settings
markdown: kramdown
